GO = go
ARGS = build -ldflags
LDFLAGS = -H windowsgui
BUILD_DIR = .
BINARY = ecm-distro-tools-ui.exe

# disable warnings
.EXPORT_ALL_VARIABLES:
CGO_CFLAGS=$(shell go env CGO_CFLAGS) -w

$(BINARY): main.go
	$(GO) $(ARGS) "$(LDFLAGS)" $(BUILD_DIR)

clean:
	rm -f $(BINARY)
